### ISSUE TITLE
Cursor shape does not change for "startInInsertMode"

### ISSUE THREAD

**Issue by ghost** [aioutecism/amVim-for-VSCode#219] opened 2018-06-26 16:41 UTC
When startInInsertMode is enabled and you switch to a new tab, the extension goes into insert mode but the cursor shape remains a block leading to confusion.

**Comment by alisonatwork** [comment] 2022-11-13 09:38
I can't reproduce this and since the user who reported it has been deleted, I will close this issue.

**Closed by alisonatwork** 2022-11-13 09:38 UTC
Labels: bug
