### ISSUE TITLE
repeat partial when typing '.'

### ISSUE THREAD

**Issue by Bruce313** [aioutecism/amVim-for-VSCode#76] opened 2016-04-25 08:59 UTC
Hi, Thanks for The Great Work!

When I typing 'a' and I got 'hint-list' like 'abc, adefad, aefe', then I typing the 'Enter‘
So this will INPUT 'abc'
Then typing '.', VIM should Enter 'abc', not 'a'.

**Comment by aioutecism** [comment] 2016-04-25 11:45
Duplicate of https://github.com/aioutecism/amVim-for-VSCode/issues/69#issuecomment-213701749
Deletion and autocomplete are not recorded now.

**Closed by aioutecism** 2016-04-25 11:45 UTC
Labels: duplicate
