### ISSUE TITLE
Support number modifier for "p"

### ISSUE THREAD

**Issue by giggio** [aioutecism/amVim-for-VSCode#25] opened 2016-01-12 17:01 UTC
We cant do `3p` at the moment to paste yanked text 3 times. I use this all the time, please support it.

**Comment by aioutecism** [comment] 2016-01-13 01:01
This is in the roadmap and will be supported soon.

**Comment by vitorgalvao** [comment] 2016-04-15 18:07
Duplicate of #20.

**Comment by aioutecism** [comment] 2017-04-12 04:36
Supported in 1.22.0.

**Closed by aioutecism** 2017-04-12 04:36 UTC
Labels: enhancement
