### ISSUE TITLE
When I use the mouse cursor, the cursor will always move forward one character at a time.

### ISSUE THREAD

**Issue by fenglinnet** [aioutecism/amVim-for-VSCode#182] opened 2017-06-13 07:57 UTC
When I use the mouse cursor, the cursor will always move forward one character at a time.This often leads to copy&cut lost the last character.Maybe I'm not a depth of vim users, there are still heavy mouse operation.If this behavior can change or have a setting, that will be happy:)

**Comment by aioutecism** [comment] 2017-12-19 08:29
Can't reproduce on the latest version.
Cloud you upload screenshots to the issue?

**Comment by aioutecism** [comment] 2018-01-16 10:51
Closing since not reproducible.

**Closed by aioutecism** 2018-01-16 10:51 UTC
Labels: invalid
