### ISSUE TITLE
Unable to move/edit when trying to repeat with dot-command

### ISSUE THREAD

**Issue by mpseidel** [aioutecism/amVim-for-VSCode#77] opened 2016-04-25 19:00 UTC
Thanks for adding the `.`-command!

Unfortunately the plugin seems to completely freeze up when using the `.`-command occasionally.

I am not sure how to reproduce it exactly but it seems to happen regularly when I try to repeat a `cw`-command:

1. Move to the beginning of a word `foo`
2. `cw "bar" ESC`
3. Move to begging of other occurence of `foo`
4. `.`

=> Cursor remains in NORMAL-Mode and does not react to any subsequent commands

**Comment by aioutecism** [comment] 2016-04-26 02:07
Thanks for reporting!

I can't reproduce on OSX 10.11.4, VSCode 1.0.0, amVim 1.4.1.
What is your environment?

**Comment by mpseidel** [comment] 2016-04-26 04:06
I use Windows 10.

**Comment by aioutecism** [comment] 2016-04-27 10:19
I'll look into this one during golden week.
Please give me some time.

**Comment by shamrin** [comment] 2016-06-10 09:02
I've also had this problem a couple of times. On OS X 10.11, VSCode 1.2.0, amVim 1.8.0.

Here's how to reproduce it: do `dw`. Then do `j` `.` `j` `.` … in quick succession. Eventually amVim will stop reacting to commands (but it will show them in status bar). Demo:

![dot-bug](http://i.imgur.com/KWLLMpz.gif)

**Comment by aioutecism** [comment] 2016-08-30 08:41
This should be fixed in 1.10.2.
This is because a wired bug of v8 engine.
If anyone are interested, take a look at the fix: https://github.com/aioutecism/amVim-for-VSCode/commit/83a7c1184699a095759f6e04f7344658f057e26b

**Closed by aioutecism** 2016-08-30 08:41 UTC
Labels: bug
