### ISSUE TITLE
Navigate through blank lines using { and }

### ISSUE THREAD

**Issue by endel** [aioutecism/amVim-for-VSCode#110] opened 2016-07-11 07:17 UTC
This is one of my most used navigation patterns. `{` should go to the previous blank line and `}` to the next one.

**Comment by tobia** [comment] 2016-07-18 18:11
I think this issue will be marked as duplicate of #1 

Still, I use `{` and `}` all the time too, so I really hope someone with the knowledge will implement it soon!

**Comment by d-sparks** [comment] 2016-10-21 15:49
+1

**Comment by aioutecism** [comment] 2017-04-13 05:54
Supported in 1.23.0.

**Closed by aioutecism** 2017-04-13 05:54 UTC
Labels: enhancement
